### ISSUE TITLE
Remove MAX_LIMIT

### ISSUE THREAD

**Issue by marks** [xmunoz/sodapy#13]
https://github.com/xmunoz/sodapy/blob/0bcb2d16694a140c20feca68009e0e24d8399ca9/sodapy/constants.py#L1

MAX_LIMIT does not apply to SODA 2.1 endpoints

**Comment by chrismetcalf** [comment]
:+1:

**Comment by xmunoz** [comment]
Ok, I guess it's a little weird to do this checking preemptively, I'll open a PR.

**Comment by xmunoz** [comment]
It's in the newest release.
