### ISSUE TITLE
Support uploading and replacing shapefiles

### ISSUE THREAD

**Issue by nathanhilbert** [xmunoz/sodapy#18]
See @timwis's https://github.com/xmunoz/sodapy/issues/16#issuecomment-191962586 on uploading shapefiles to Socrata.  Functionality can be replicated from [soda-java](https://github.com/socrata/soda-java/blob/a23dea2e75937abb823267126677dc4e8488f52e/src/main/java/com/socrata/api/SodaImporter.java#L124)

**Comment by xmunoz** [comment]
The [Socrata Publishing API](https://socratapublishing.docs.apiary.io/) supersedes this library, and  supports shapefile uploads. It's been almost 5 years, if I haven't gotten to this by now, I don't think I ever will.
