### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by timwis** [xmunoz/sodapy#22]
Just noticed there's a `create` method and a `get_metadata` method using the same endpoint, but no `update` method. Here's some relevant info from Socrata on the `/api/views.json` endpoint:

> `PUT` to `/api/views/unique_id.json` with a subset of what you want to update.  For instance, if you want to add tags to the previously created dataset (currently this is the only way to add tags), you can simply `PUT` to the endpoint with:
```json
{
  "tags": ["these", "words", "are", "tags"]
}
```
> You'll probably also want to make this dataset public and publish it, so you'll want to perform the two following operations as well:
`PUT /views/unique_id?method=setPermission&value=public.read`
`POST /api/views/unique_id/publication.json`

> One important thing to note about updates is that if you want to update something within the "custom metadata", you will have to copy the entire metadata object since it does a replace.

Note that I've heard over the year(s) that the views endpoint is/will be deprecated, but until there's a clear alternative it probably makes sense to continue to use it.

Anyway, I may get a chance to work on this, but wanted to post the details here in case anyone else is interested.

**Comment by chrismetcalf** [comment]
Be very careful with the `/api/views/$id.json` endpoint - there are things you can do by patching that payload that can damage your dataset or visualization configuration. In particular, updates to the `metadata` key need to be very carefully merged with the existing content in that part of the object, or you can overwrite dataset configuration that also resides there. Its best to make sure you're only `PUT`ting the keys you want to actually update, and leave everything else out.

I've probably been one of those people over the years telling you about our plans to replace this API, as it is my top priority for replacement. However, until I can share more concrete plans with you, you're free to (carefully) use it.

With great power comes great responsibility. 😉

**Comment by xmunoz** [comment]
Lolz you guys 😸 

I should have time to implement something this weekend. Thanks for the heads up, and I'll let you know if I have any more questions. As always, pull requests are always welcome. If I get to it first though, I will likely ask you both of you to review.

**Comment by timwis** [comment]
That's awesome! Thanks :D
