### ISSUE TITLE
Exception: Unknown response format: application/json

### ISSUE THREAD

**Issue by alex-wap** [xmunoz/sodapy#29]
I deployed an application three months ago using sodapy. It was fully functional up until Monday, November 28. On my deployed instance, I get "502 Bad Gateway". Running locally, I get the following error:

```
File "/Users/File/Path/Crime.py", line 12, in get_crimes
crimes = client.get("cuks-n6tp",limit=3000)

File "/usr/local/lib/python2.7/site-packages/sodapy/__init__.py", line 237, in get
params=params)

File "/usr/local/lib/python2.7/site-packages/sodapy/__init__.py", line 368, in _perform_request
.format(content_type))

Exception: Unknown response format: application/json
```

I don't understand the exception. The data set is here and clearly json: https://data.sfgov.org/resource/cuks-n6tp.json

Let me know if this is the wrong place to post this question.

Thanks,
Alex

**Comment by alex-wap** [comment]
I modified my _ _ init _ _.py. I commented out (start line 353):
```
        # content_type = response.headers.get('content-type').strip().lower()
        # if re.match(r'application\/json;\s*charset=utf-8', content_type):
        #     return response.json()
        # elif re.match(r'text\/csv;\s*charset=utf-8', content_type):
        #     csv_stream = StringIO(response.text)
        #     return [line for line in csv.reader(csv_stream)]
        # elif re.match(r'application\/rdf\+xml;\s*charset=utf-8', content_type):
        #     return response.content
        # elif re.match(r'text\/plain;\s*charset=utf-8', content_type):
        #     try:
        #         return json.loads(response.text)
        #     except ValueError:
        #         return response.text
        # else:
        #     raise Exception("Unknown response format: {0}"
        #                     .format(content_type))
```
and just added `return response.json()`

This works for my application. The regex for json: `re.match(r'application\/json;\s*charset=utf-8', content_type):` on line 354 does not match `application/json`. Maybe my data source changed its header? Should the regex match json without charset specified?

Thanks for reading.

**Comment by timwis** [comment]
What version of python are you using? It may not be related, but I had to upgrade python in order to meet Socrata's [new security requirements](https://support.socrata.com/hc/en-us/articles/231975987).

**Comment by xmunoz** [comment]
Hey, yeah I agree that this regex could definitely be more flexible about what it matches. I'll push an update for that soon.

**Comment by xmunoz** [comment]
Gah, referenced wrong issue number in commit message. Anyway, 48634ace7.

**Comment by alex-wap** [comment]
@timwis I'm using Python 2.7.6. Thanks for the link, I'll have to upgrade.

@xmunoz Thanks for the speedy fix!

**Comment by bjacobel** [comment]
Just ran into this as well, seems Socrata may have updated the content-type headers for a bunch of datasets around 11/28 midnight UTC. Awesome to see there's already a fix, thanks @xmunoz!

**Comment by chrismetcalf** [comment]
Thanks @xmunoz!

**Comment by xmunoz** [comment]
Thank you everybody for the bug reporting and the thanks! I came for the data, but stayed for the amazingly supportive Socrata open source dev community :champagne:.
