### ISSUE TITLE
Managing attachments

### ISSUE THREAD

**Issue by blah238** [xmunoz/sodapy#3]
Does this library let you manage attachments on datasets? If not I would love to see such a feature. I see that the Java API has [`getAttachments()`](https://github.com/socrata/soda-java/blob/a23dea2e75937abb823267126677dc4e8488f52e/src/main/java/com/socrata/model/importer/Metadata.java#L146) and [`setAttachments()`](https://github.com/socrata/soda-java/blob/a23dea2e75937abb823267126677dc4e8488f52e/src/main/java/com/socrata/model/importer/Metadata.java#L151) methods.

**Comment by xmunoz** [comment]
I did not write any special functionality for this, so the answer to your questions is probably "no". I'll look at the Java API and see if I can port that.

**Comment by xmunoz** [comment]
The current status of this is that there is now an [available method](https://github.com/xmunoz/sodapy#download_attachmentsdataset_identifier-content_typejson-download_dirsodapy_downloads) to download all of the attachments associated with a dataset. Setting attachments is not currently supported by sodapy, and probably won't be until Socrata's API explicitly provides an endpoint for this.
