### ISSUE TITLE
replace() method using CSV

### ISSUE THREAD

**Issue by gamonsalve** [xmunoz/sodapy#35]
Hi
I'm trying to replace a dataset using .replace() method. I use a CSV that contains headers. does replace() method accept CSV with headers?or no?
Thanks

**Comment by xmun0x** [comment]
It should. Are you experiencing any errors or unexpected behaviour? If so, could you please paste in the code snippet and input data, along with the response.

**Comment by gamonsalve** [comment]
It does not work for me, but I solved the problem converting csv data to Json, and then I used replace method. Thanks
