### ISSUE TITLE
Confusing error for csv upsert

### ISSUE THREAD

**Issue by James-OHara** [xmunoz/sodapy#36]
I'm using SodaPy to do a simple upsert of a data file to an empty dataset (contains columns but no data). However, I'm getting a confusing error message that Socrata cannot recognize the payload type file, even though that's supposed to be supported. This is a properly formatted comma-separated file with Unix line endings. Traceback of the error in Python 2.7 is below. The error is Python 3 is different and attached here.

Traceback (most recent call last):
  File "dtg_data_upload.py", line 21, in <module>
    conn.upsert("8ect-6jqj ", uploadcsv)
  File "C:\Python27\lib\site-packages\sodapy\__init__.py", line 249, in upsert
    return self._perform_update("post", resource, payload)
  File "C:\Python27\lib\site-packages\sodapy\__init__.py", line 307, in _perform_update
    " and file-types are supported.".format(type(payload)))
Exception: Unrecognized payload <type 'file'>. Currently only list-, dictionary-, and file-types are supported.
[python3error.txt](https://github.com/xmunoz/sodapy/files/1314946/python3error.txt)

**Comment by xmunoz** [comment]
Thanks for letting me know! This probably never worked in python2. I've pushed a short-term fix for you [here](https://github.com/xmunoz/sodapy/commit/f4bb48d6893b887bb775515d194fe0fbe5f0436c). Unfortunately this is not python3 compatible, so I cannot release it this way. Once I figure out a solution that works for both, I'll roll a new version.

**Comment by James-OHara** [comment]
Thank you!

**Comment by xmunoz** [comment]
Just finished [releasing](https://pypi.python.org/pypi/sodapy/1.4.4) the bugfix. Enjoy!
