### ISSUE TITLE
Fails installation via pip

### ISSUE THREAD

**Issue by dhmspector** [xmunoz/sodapy#4]
Was trying to install the API in my virtual env, and got the following failure, other packages install and work just fine.   Any suggestions?  

(datamanager) Zeitgeist:datamanager spector$ pip install sodapy
Collecting sodapy
  Using cached sodapy-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/kh/q9217zqs1wdf6g7yzczz09br0000gn/T/pip-build-jkmfj12g/sodapy/setup.py", line 4, in <module>
        execfile("sodapy/version.py")
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kh/q9217zqs1wdf6g7yzczz09br0000gn/T/pip-build-jkmfj12g/sodapy

**Comment by xmunoz** [comment]
You might be using python3? In this case. here are the instructions for building this project from source:

1. Setup and activate your python3 virtualenv

    virtualenv --no-site-packages -p python3 venv_py3
    source venv_py3/bin/activate

2. Install future.

    pip3 install future

3. Clone the repo and build the source.

    git clone git@github.com:xmunoz/sodapy.git
    cd sodapy/
    git checkout python3
    python3 setup.py install
    python3 setup.py install

That last line is not a typo. For some reason you need to `install` twice, it dies the first time on `requests`, and succeeds the second time. I don't know why...

4. Once it's finished, the binaries should be moved into the correct location (in your virtualenv), so you can clean up the source.
    
    cd ..
    rm -rf sodapy/


I've been meaning to write this all down for a minute. Thanks for giving me a good reason.

**Comment by xmunoz** [comment]
Did this solve your problem @dhmspector?

**Comment by dhmspector** [comment]
Yes, it did!  Thank you!
