### ISSUE TITLE
No parameter to filter and get data between specific dates

### ISSUE THREAD

**Issue by aghogre** [xmunoz/sodapy#40]
Suppose I want data from 01-01-2017 to 01-08-2017 by using API , specially for this endpoint- https://data.medicaid.gov/resource/tau9-gfwr.json
But I am not able to find anything related to this.

**Comment by xmunoz** [comment]
sodapy is a wrapper library for Socrata's [SODA](https://dev.socrata.com/). This is probably a question that you should ask them. 

However, if your issue is related to the fact that their API supports this kind of filtering, but this library does not, could you provide a sample query?
