### ISSUE TITLE
Tutorials and Usage Examples

### ISSUE THREAD

**Issue by matthewwritter** [xmunoz/sodapy#41]
New users, particularly those without experience with Socrata, might benefit from a tutorial, plus a few template projects. 

I'd be happy to start a PR if this sounds interesting! Let me know if there are any data sources or pieces of functionality that you think would be particularly good. Otherwise I'll dive in and figure something out.

**Comment by xmunoz** [comment]
Yeah, go for it!

**Comment by matthewwritter** [comment]
Great, I'll get going on it. Who knows how long it will take, but I'll aim for a minimum viable product in 1wk

**Comment by matthewwritter** [comment]
I took a run at it, but found that both "sandbox.demo.socrata.com" and "opendata.socrata.com" didn't work, giving an error when I try the get method. I'm trying "data.lacity.org" , but am not sure what parts of the string should go were. Could you give me a pointer?
