### ISSUE TITLE
Unable to get data on map

### ISSUE THREAD

**Issue by chrisblinn** [xmunoz/sodapy#42]
I am running into an issue when trying to pull points from a map.

Here is the dataset:
https://data.austintexas.gov/dataset/Address-Points/mkjr-t5r2

Code (python 3.x)
`from sodapy import Socrata`
`client = Socrata("data.austintexas.gov", None)`
`addresspoints = client.get("mkjr-t5r2")`

Response:
`WARNING:root:Requests made without an app_token will be subject to strict throttling limits.`
`Traceback (most recent call last):`
`  File "C:\Scripts\Socrata\getSocrataData.py", line 3, in <module>`
`    addresspoints = client.get("mkjr-t5r2")`
`  File "C:\Python\Python36\lib\site-packages\sodapy\__init__.py", line 237, in get`
`    params=params)`
`  File "C:\Python\Python36\lib\site-packages\sodapy\__init__.py", line 352, in _perform_request`
`    _raise_for_status(response)`
`  File "C:\Python\Python36\lib\site-packages\sodapy\__init__.py", line 406, in _raise_for_status`
`    raise requests.exceptions.HTTPError(http_error_msg, response=response)`
`requests.exceptions.HTTPError: 404 Client Error: Not Found.`
`	Dataset '_mkjr-t5r2' was not found`

I've tested other datasets without issue.

**Comment by xmunoz** [comment]
The problem seems to be the way these geospatial endpoints are constructed. sodapy doesn't currently support endpoints of the form:
https://data.austintexas.gov/api/views/9s7j-tygf/rows.json

I won't have time to fix this in the next few days, but if you take a look here, it should be a pretty straight forward pull request:
https://github.com/xmunoz/sodapy/blob/master/sodapy/__init__.py#L434

**Comment by xmunoz** [comment]
Disregard my previous comment. The problem is actually that the dataset ID in the url is not the same as the one for the API endpoint for whatever reason. You can find the correct dataset identifier in Export > SODA API > API Endpoint

It works with the correct identifier.

```
> client.get("9s7j-tygf", limit=2)
[{'created_by': 'Automated', 'full_street_name': '14408 CELESTIAL LN', 'address': '14408', 'objectid': '709047', 'street_name': 'CELESTIAL', 'parent_place_id': '1486', 'place_id': '69441', 'segment_id': '3428213', 'created_date': '2003-03-26T00:00:00.000Z', 'the_geom': {'type': 'Point', 'coordinates': [-97.626872464507, 30.413745580484]}, 'street_type': 'LN', 'modified_by': 'SJENSEN', 'address_type': '1', 'modified_date': '2010-04-05T17:38:34.000Z'}, {'created_by': 'GIS-sclamons', 'full_street_name': '11407 MUSKET RIM', 'address': '11407', 'objectid': '694286', 'street_name': 'MUSKET RIM', 'parent_place_id': '5349', 'place_id': '3067941', 'segment_id': '2022072', 'created_date': '2002-01-22T00:00:00.000Z', 'the_geom': {'type': 'Point', 'coordinates': [-97.928297314234, 30.288360241308]}, 'address_type': '1', 'modified_date': '2002-01-22T00:00:00.000Z'}]
```

**Comment by chrisblinn** [comment]
Thank you – I noticed that as well when you responded the first time.  I have done some testing and the ID was certainly the culprit.  Thank you for your assistance.

[http://gisinc.com/wp-content/uploads/2016/02/gisinc_email_signature.gif]
Christopher Blinn, M.S., GISP
Senior Solutions Engineer
Geographic Information Services, Inc. (GISinc)
O: 205.725.5874
chris.blinn@gisinc.com<mailto:chris.blinn@gisinc.com>
gisinc.com
An Employee-Owned Company
Learn more about Cost Map for Water Utilities, powered by RSMeans data
http://gisinc.com/services/cost-map-water-utilities
