### ISSUE TITLE
python 3 install instructions incomplatable with build tools

### ISSUE THREAD

**Issue by bgrayburn** [xmunoz/sodapy#5]
Thanks for this library! It will greatly simplify my workflow if I can just resolve one thing. I'm trying to use this library in python 3 inside of a docker container. Because errors during the Docker build process cause the build to stop, having to run python install setup.py twice isn't a solution. I imagine this is a problem with any build tool similar to docker. Is it possible to eliminate the need for errors in the install process?

**Comment by xmunoz** [comment]
[Does this help?](https://github.com/xmunoz/sodapy/issues/4)

I should really add this to the readme...

**Comment by bgrayburn** [comment]
unfortunately not. The problem is the error being thrown by the first time you type `python3 setup.py install`.  This error stops the build process in a Docker build. Is there any way to eliminate the need for this error being thrown?

**Comment by xmunoz** [comment]
I've just released a python3-compatible update. No special install instructions required :)

**Comment by bgrayburn** [comment]
thank you! awesome
