### ISSUE TITLE
Add GeoJSON as supported content-type

### ISSUE THREAD

**Issue by ktollas** [xmunoz/sodapy#55]
Can you add support for pulling GeoJSON formats from Socrata?

Socrata format reference: https://dev.socrata.com/docs/formats/#,

I see in your _perform_request function (starting at line 484 in https://github.com/xmunoz/sodapy/blob/master/sodapy/__init__.py) that there is no option for setting the content-type to geojson

**Comment by ktollas** [comment]
I fixed locally by adding the line

elif re.match(r'application\/vnd.geo\+json', content_type):
        return response.json()

**Comment by xmunoz** [comment]
Fixed by 38616b5a829f2f4
