### ISSUE TITLE
content-type fails

### ISSUE THREAD

**Issue by ducovrossem** [xmunoz/sodapy#6]
I am having trouble with the content-type in sodapy. Specifically - this is for the RDW dataset. 

Anyway, running

```
from sodapy import Socrata
client = Socrata("opendata.rdw.nl", "token1234", "username=email@email.com", password="XXX")
client.get("/resource/m9d7-ebf2.csv", limit=4)
```

From this I get the response:
```
Exception: Unknown response format: text/csv;charset=utf-8
```

There seems to be a missing space here in the header response so that the if statement fails on line 205 in `__init__.py`

```
text/csv;charset=utf-8
```
Instead of 
```
text/csv; charset=utf-8
```

The same happens for `.json` instead of `.csv`

Is this an RDW issue for excluding a space from the header? Is there any workaround for this?

**Comment by chrismetcalf** [comment]
Looks like we should be more forgiving around the missing space there.

@xmunoz: I've submitted a pull request that I believe will fix this: https://github.com/xmunoz/sodapy/pull/7
