### ISSUE TITLE
Feature request: Option to disable the throttling limit warning

### ISSUE THREAD

**Issue by eelcohn** [xmunoz/sodapy#68]
Hi,

When no `app_token` is provided a Warning is logged: 
> Requests made without an app_token will be subject to strict throttling limits.

Would it be possible to disable that warning? I know that working without an `app_token` limits the amount of requests to an OpenData API, and I don't want my logfile to fill up with Warnings that I already know about.

**Comment by xmunoz** [comment]
If you don't want warnings, add an `app_token` :)

**Comment by xmunoz** [comment]
The other option it to configure the logging level in your code: https://docs.python.org/3/library/logging.html#logging.Logger.setLevel
