### ISSUE TITLE
support automatic pagination

### ISSUE THREAD

**Issue by afeld** [xmunoz/sodapy#69]
Hey, nice library! I was thinking, it would be useful for the package to support pagination for `get()` (maybe other methods), to make it easier to retrieve large datasets. Maybe an optional `paginate=True` keyword argument? Thanks!

**Comment by xmunoz** [comment]
As it stands now, you can implement your own pagination with the `$limit` and `$offset` [SoQL keywords](https://dev.socrata.com/docs/queries/). If you want to take a stab at implementing something like this with a default limit (1K records?) I think that would be be a  real benefit for many users of this library.
