### ISSUE TITLE
Support for Socrata Headers?

### ISSUE THREAD

**Issue by RUDelerius** [xmunoz/sodapy#76]
Sorry if this isn't the appropriate place to ask about this.  Please close it if not.  I'm working on my very first python script and I've been looking for a way to get the field names and data types for just the record set returned by my query.  

client.get_metadata() returns all fields, but I want to build a dictionary using just the fields in my results.

Response headers X-SODA2-Fields (and X-SODA2-Types) should return a set limited to just the fields returned by the get() request.  

Is this something that could be supported?  I can see in utils.py the response header is processed for response codes, but cannot find anything that processes these fields.  Or maybe I should just use requests instead?

**Comment by xmunoz** [comment]
Totally! I can take a look at this later in the week. If you want to try to implement it before then, feel free to send a PR.

**Comment by xmunoz** [comment]
After thinking about this more carefully, yeah I think you should just use requests directly. If I understand your request correctly,  what you want is actually something that constitutes the "Transform" part of ETL. This library is primarily concerned with the "Extract" layer.

**Comment by RUDelerius** [comment]
Thank you for your consideration.
