### ISSUE TITLE
Optional client.get "limit" defaults to 1000.  Need limit=none

### ISSUE THREAD

**Issue by snakyjake1** [xmunoz/sodapy#83]
How do I get all the records from a dataset?
The default limit is 1000, and I don't see a way to change the limit to none.

```
client = SocrataAPI(
    site,
    key,
    email,
    password
    )

dataset= client.get('g62h-syeh')
print(len(dataset))
```

1000

**Comment by darrylackley** [comment]
There is a `get_all` method in the API, line 417 of the `socrata.py` file:

https://github.com/xmunoz/sodapy/blob/master/sodapy/socrata.py
