### ISSUE TITLE
Needs update: Example 01: Basic Queries

### ISSUE THREAD

**Issue by lennonzheng** [xmunoz/sodapy#84]
Hi there. 

It seems like the domain has moved away from https://opendata.socrata.com to evergreen or tyler tech? Which results in most of the links in this notebook to be 404. 

Could the contributor look into this? 

A lot of links from Socrata webpage are also 404, that makes me think if Socrate has moved away to other platform? If so, could someone shared with me where can I get the data? 

Many thanks!!

**Comment by xmunoz** [comment]
I'm not associated with any of these organizations, but I would gladly accept a pull request that addresses this.
