### ISSUE TITLE
This repository will be archived on Aug 31

### ISSUE THREAD

**Issue by xmunoz** [xmunoz/sodapy#87]
Hello friends,

7 years ago I started developing this project. Since then, it has become the most popular client library for the SODA API. At that time, I was just beginning my journey as a software developer. 7 years later, I am a busy consultant juggling many different clients. As such, I no longer have the time or energy to maintain this project as a volunteer.

I have reached out to Tyler Technologies to see if they would like to continue maintaining sodapy, or pay me to do so via Github Sponsors. The reply they sent me indicates that they do not want to do either of those things, so I will be locking this repository to any changes in the next two weeks. Before I do that, I would be happy to review and merge Pull Requests that address any existing issues. Additionally, I will also cut one final release.

Feel free to comment below if you have any concerns. If you have contributed to or used this project in any capacity over the last 7 years, thank you!

-Cristina

**Comment by darrylackley** [comment]
Just a note to say thanks for all the work you've put into this; it's been immensely useful.
